"""Headless Xorg server management for nvidia-settings access."""

from __future__ import annotations

import logging
import subprocess
import time
from pathlib import Path

log = logging.getLogger(__name__)

XORG_CONF_PATH = Path("/etc/X11/xorg.conf.d/10-nv-fancurve.conf")
XORG_CONF_TEMPLATE = """\
# Generated by nv-fancurve. Do not edit manually.
Section "ServerFlags"
    Option "AllowEmptyInput" "true"
    Option "AutoAddDevices" "false"
    Option "AutoEnableDevices" "false"
    Option "AutoAddGPU" "false"
EndSection

Section "Monitor"
    Identifier "nv-fancurve-monitor"
    HorizSync   28.0-80.0
    VertRefresh 48.0-75.0
    Modeline "1024x768" 65.0 1024 1048 1184 1344 768 771 777 806 -hsync -vsync
EndSection

Section "Device"
    Identifier "nv-fancurve-device"
    Driver "nvidia"
    BusID "{bus_id}"
    Option "AllowEmptyInitialConfiguration" "True"
    Option "Coolbits" "28"
EndSection

Section "Screen"
    Identifier "nv-fancurve-screen"
    Device "nv-fancurve-device"
    Monitor "nv-fancurve-monitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1024x768"
    EndSubSection
EndSection
"""


def detect_bus_id(gpu_id: int = 0) -> str:
    """Find PCI bus ID for the given NVIDIA GPU, formatted for Xorg."""
    result = subprocess.run(
        ["nvidia-smi", f"--id={gpu_id}", "--query-gpu=pci.bus_id", "--format=csv,noheader"],
        capture_output=True,
        text=True,
        check=True,
    )
    out = result.stdout.strip()
    parts = out.split(":")
    if len(parts) != 3:
        raise ValueError(f"Cannot parse PCI ID: {out!r}")

    bus = int(parts[1], 16)
    device_func = parts[2].split(".")
    if len(device_func) != 2:
        raise ValueError(f"Cannot parse PCI device/function: {out!r}")
    device = int(device_func[0], 16)
    func = int(device_func[1])
    return f"PCI:{bus}:{device}:{func}"


def write_xorg_conf(bus_id: str | None = None) -> None:
    """Write the Xorg config to /etc/X11/xorg.conf.d/."""
    if bus_id is None:
        bus_id = detect_bus_id()
    XORG_CONF_PATH.parent.mkdir(parents=True, exist_ok=True)
    XORG_CONF_PATH.write_text(XORG_CONF_TEMPLATE.format(bus_id=bus_id))
    log.info("Wrote Xorg config to %s with %s", XORG_CONF_PATH, bus_id)


def is_xorg_running(display: str = ":1") -> bool:
    """Check whether Xorg is running on the given display."""
    socket = Path(f"/tmp/.X11-unix/X{display.lstrip(':')}")
    return socket.exists()


def start_xorg(display: str = ":1") -> subprocess.Popen[bytes]:
    """Start a headless Xorg on the given display."""
    if is_xorg_running(display):
        raise RuntimeError(f"Xorg already running on {display}")

    proc = subprocess.Popen(
        ["Xorg", display, "-config", str(XORG_CONF_PATH), "-nolisten", "tcp"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    for _ in range(100):
        if is_xorg_running(display):
            return proc
        time.sleep(0.1)

    proc.terminate()
    raise RuntimeError(f"Xorg failed to start on {display}")
